import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBarClient from "../_components/Navbar/NavBarClient";
import "../globals.css";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <NavBarClient />
          <div className="flex flex-col flex-1">
            <header className="bg-white shadow-md p-4">
              <h1 className="text-xl font-semibold">
                Welcome to the Dashboard
              </h1>
            </header>

            <main className="flex-1 p-6">{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
